### ISSUE TITLE
the dot is always shown

### ISSUE THREAD

**Issue by 532910** [m3sv/PlainUPnP#60] opened 2020-06-19 11:47 UTC
The dot should not be shown when it's just running:

![image](https://user-images.githubusercontent.com/14617699/85129368-a2101900-b23b-11ea-970f-fd631fe6caa1.png)
![image](https://user-images.githubusercontent.com/14617699/85129381-aa685400-b23b-11ea-9209-f904247788af.png)

And I knot that it's fixable: https://gitlab.com/proninyaroslav/libretorrent/-/issues/222

**Comment by m3sv** [comment] 2020-06-19 13:18
Thanks, will take a look at libretorrent's implementation.

**Comment by m3sv** [comment] 2020-06-19 16:08
Done, will be added with new release. Same as Notification, will work either by reinstalling the app, or navigating to settings and manually changing them.

**Comment by 532910** [comment] 2020-06-19 20:11
> Same as Notification, will work either by reinstalling the app, or navigating to settings and manually changing them.

Yep, I know (:

**Comment by m3sv** [comment] 2020-06-27 08:52
Will be closing this now, feel free to reopen if the issue is still there.

**Closed by m3sv** 2020-06-27 08:52 UTC
